### ISSUE TITLE
ROS costmap 

### ISSUE THREAD

**Issue by Leedk3** [mit-acl/mppi_numba#1]
Hi there,

Thank you for sharing your amazing work!
I am trying to change your unicycle model to ackermann-based vehicle model.
Also, I want to deploy robot for the real-world test.

To do this, I am looking into your test code, and found "use_costmap" parameter.
After your first release, is there any progress for ROS costmap version?

Again, thank you very much!

Best,

**Comment by xiaoyi-cai-acl** [comment]
Hi, thank you for your interest! 

There were some preliminary efforts in interfacing with ROS Costmap2D, but our experience suggested that the overhead in converting Costmap2D in cpp and porting the data to python via pybind11 was quite significantly (at least compared to the performance gain due to GPU). Therefore, we did not pursue that costmap2d option further. 

However, if you do want to go down this route, an option is to use pybind11 to initialize a MPPI_Numba object in a cpp node. Then:
1. Convert costmap2d objects in your cpp node to corresponding pybind arrays (e.g., lethal, unknown, etc.) 
2. Write a new python function for MPPI_Numba to process the pybind arrays. 

Alternatively, you can have a cpp node that publishes a custom message that contains relevant info from costmap2d (e.g., obstacles and unknown cells). The message can then be subscribed by a python node that holds the MPPI_Numba object. This should be easier to do.

**Comment by Leedk3** [comment]
Oh, I am looking into the alternative method by generating costmap on the other packages. 
Thank you for your fast reply!
You can close this issue then.

**Comment by brilianputraa** [comment]
> Oh, I am looking into the alternative method by generating costmap on the other packages. Thank you for your fast reply! You can close this issue then.

Hi may I know what package you used for generating the costmap?

**Comment by xiaoyi-cai** [comment]
Hi there, I think you have many options. Typical ones are:
* [grid_map](https://github.com/ANYbotics/grid_map)
* [costmap_2d](http://wiki.ros.org/costmap_2d)
* Or just other occupancy mapping tools.

Note that grid_map follows a different convention compared to the [ROS occupancy grid message](http://docs.ros.org/en/melodic/api/nav_msgs/html/msg/OccupancyGrid.html), so you have to use grid_map's [conversion functions](http://docs.ros.org/en/jade/api/grid_map_ros/html/classgrid__map_1_1GridMapRosConverter.html) accordingly.

You just have to write a ROS subscriber to those maps and pass the maps to the planner.

**Comment by brilianputraa** [comment]
> Hi there, I think you have many options. Typical ones are:
> 
> * [grid_map](https://github.com/ANYbotics/grid_map)
> * [costmap_2d](http://wiki.ros.org/costmap_2d)
> * Or just other occupancy mapping tools.
> 
> Note that grid_map follows a different convention compared to the [ROS occupancy grid message](http://docs.ros.org/en/melodic/api/nav_msgs/html/msg/OccupancyGrid.html), so you have to use grid_map's [conversion functions](http://docs.ros.org/en/jade/api/grid_map_ros/html/classgrid__map_1_1GridMapRosConverter.html) accordingly.
> 
> You just have to write a ROS subscriber to those maps and pass the maps to the planner.

Thank you for your prompt response and recommendations!, okay I will take a look into it

**Comment by xuyuxiu83** [comment]
> Hi there, I think you have many options. Typical ones are:
> 
> * [grid_map](https://github.com/ANYbotics/grid_map)
> * [costmap_2d](http://wiki.ros.org/costmap_2d)
> * Or just other occupancy mapping tools.
> 
> Note that grid_map follows a different convention compared to the [ROS occupancy grid message](http://docs.ros.org/en/melodic/api/nav_msgs/html/msg/OccupancyGrid.html), so you have to use grid_map's [conversion functions](http://docs.ros.org/en/jade/api/grid_map_ros/html/classgrid__map_1_1GridMapRosConverter.html) accordingly.
> 
> You just have to write a ROS subscriber to those maps and pass the maps to the planner.

Hi, thanks for the awesome work!

I'm currently working on a planning pipeline that uses ROS and various 2D/2.5D map representations such as:
- grid_map
- costmap_2d
- ROS OccupancyGrid

Before I invest time on conversions, I wanted to ask whether elevation_mapping_cupy can be used as a **direct alternative** to those mapping tools for planning purposes.

Specifically, can the elevation map output be used as a substitute for grid_map / costmap_2d? Do you suggest any examples  for using elevation_mapping_cupy in a planning stack (e.g., ROS navigation)?

Thanks in advance for your help!

**Comment by xiaoyi-cai-acl** [comment]
Hi I'm not an expert on the interface between different GPU libraries, but quick googling gave me this: https://docs.cupy.dev/en/stable/user_guide/interoperability.html#numba

It seems that cupy and numba are interoperable, but I've never tried them together.

If I understand correctly, elevation_mapping_cupy is a multi-layer grid map that uses GPU. If you want to use that map representation, you need to figure out how to make the Numba MPPI planner look up the cost/feature values in the elevation_mapping_cupy.

**Comment by xuyuxiu83** [comment]
> Hi I'm not an expert on the interface between different GPU libraries, but quick googling gave me this: https://docs.cupy.dev/en/stable/user_guide/interoperability.html#numba
> 
> It seems that cupy and numba are interoperable, but I've never tried them together.
> 
> If I understand correctly, elevation_mapping_cupy is a multi-layer grid map that uses GPU. If you want to use that map representation, you need to figure out how to make the Numba MPPI planner look up the cost/feature values in the elevation_mapping_cupy.

Thanks for the clarification, that makes a lot of sense.

If the goal is to most faithfully reproduce the complete MPPI pipeline as used in your original work, which map representation would you consider the canonical or most appropriate interface for the planner?

For example, would you recommend using more conventional representations such as costmap_2d / occupancy grids / grid_map-style 2D layers (with costs queried inside the running cost), rather than more expressive GPU-based multi-layer maps like elevation_mapping?

**Comment by xiaoyi-cai-acl** [comment]
In my work, the main ideas are the uncertainty quantification (aleatoric and epistemic) for the traction predictions, and the risk-aware planning (based on CVaR and OOD avoidance), so the underlying feature selections are less relevant for a fair comparison (although the richer the features the better).

Purely from a research perspective, I would go with multi-layer grid map because you can very easily have layers for occupancy / costmap_2d. GPU-based elevation mapping library is just the GPU implementation, and you can use that if you want too.
